### ISSUE TITLE
大佬，这个直接下载的zip无法导入谷歌浏览器提示  清单文件缺失或不可读取

### ISSUE THREAD

**Issue by llllcccjjj** [krapnikkk/joy#2]

**Comment by krapnikkk** [comment]
解压后再导入

**Comment by llllcccjjj** [comment]
![image](https://user-images.githubusercontent.com/70000656/197927799-18e9d3a4-a140-493b-ab97-34fca9ac409b.png)
![image](https://user-images.githubusercontent.com/70000656/197927831-a87118c2-3bd8-46b4-8359-68267b74386c.png)
解压后导入显示这个，是谷歌浏览器太新了嘛

**Comment by llllcccjjj** [comment]
![image](https://user-images.githubusercontent.com/70000656/197931179-db12a477-30e8-4cc8-a970-e8e156106e2d.png)
导入manifest.json所在的目录还是失败了
